jacob-grahn/platform-racing-2-server

- server/pr2_moderation.php
Re-enabled privilege to kick any user from Fred, just in case. Affected line: 12.
So now it is: The player kicking has to be a temp mod, and also has to be either kicking someone less than a moderator or be Fred (4291976).
This is the last one for this file!  I promise!
> One *last* tiny change for pr2_moderation.php

- server/fns/promote_to_moderator.php
`$result` should've been `$admin_result` on line 34.
`$result` should've been `$user_result` on line 50.
Both have been changed so the server doesn't crash.
Please remove the limits on moderator promotions (1 every 6 hours) so that we can test the new promotion/demotion mechanisms.
> fix server crash in promote_to_moderator.php

- http_server/www/bans/show_record.php
- http_server/www/vault/kong_order_placed.php
An small fix on exception to only allow new line tags.
Edit: added another new line only allowed on show_record.php
> Add html prevention in exception message

- http_server/www/get_user_list.php
Lines 61-63.
On user lists (friends, ignored), it used to say "Derron" or "Carina" before the status language was updated in 2012.  Now, it says "Playing on Derron", which cuts off the server name on most names.  This change will fix that.
> Fix friends/ignored server check from 2012 update

- server/fns/artifact_first_check.php
This pull contains some key changes to the first artifact finder mechanic.  The script will now:
- Echo a prize box that says "Bubble Set" and has the bubble body as an icon
- There's too much going on when the user finds the artifact first.  Instead of popping up a congratulatory message, PM it to the user (check my code on line 45 to make sure I'm using `$db->call` correctly)
- Award the prize via gain_part() (taken from Player.php) and auto-set the prize upon return to the lobby
Of course, check my code, but this is a lot simpler than the code was before since it uses functions that already exist.  Plus, it actually works. :)
LMK if/when you merge this code and get it running on Isabel so I can test if it works for awarding it to the first finder.
> Key changes to first artifact finder mechanic

- http_server/www/get_player_info_2.php
- http_server/www/guilds_top.php
This fix was relatively simple compared to what I was expecting. I was able to simply add a line that converts `$guild->guild_name` to `htmlspecialchars($guild->guild_name)`.  I also made sure the file sends characters in UTF-8 to prevent encoding errors.
Affected lines: 4, 35
> Added protection against html parsing in client

- http_server/www/login.php
- server/fns/artifact_first_check.php
Changed \r to real new lines.
Couple of questions @jacob-grahn:
- I assume the default color for each part is set in the client?  If not, could we set the bubble body to black?  It sort of blends in with the prize popup.
- Will this award the bubble set even if the first finder has it already?  Or does gain_part check for the user having the part first?
Other than that, everything is working perfectly!
> Fix welcome/winner PMs, which display the literal text \r instead of a new line

- http_server/www/ban_user.php
- http_server/www/guild_delete.php
- http_server/www/mod/archive_message.php
- http_server/www/mod/do_lift_ban.php
- http_server/www/mod/guild_deep_info.php
- http_server/www/mod/update_account.php
- http_server/www/mod/update_guild.php
- http_server/www/remove_level.php
- server/fns/demod.php
- server/fns/promote_to_moderator.php
Adds action logging for these mod actions:
- Deleting guilds
- Lifting bans
- Banning
- Unpublishing levels
- Deleting guilds
- Archiving PM reports
This pull is a fix for #58. Please make sure it accomplishes what it set out to accomplish.
Also, I provided some fixes for the admin guild/player update/viewing tools; However, the database functions need to be updated in order to be fully functional.  See #97 for more details.
> Fix admin tools, add action logging for more mod actions

- README.md
- http_server/www/mod/ban_edit.php
- http_server/www/mod/do_lift_ban.php
- http_server/www/mod/update_guild.php
7422130 should make it so editing a guild will preserve the emblem.  The scope of the function got me the first time, then it was not defining a variable earlier in the function but calling it at that time. 
17th time's the charm, right?
Also in this pull:
- Hopefully fix ban_edit.php's checkboxes (54d4c71)
- Fix action logging in ban_edit.php (039d1ec)
- http->https in ban_edit.php (e065091)
- Fix broken redirect link in do_lift_ban.php (f96bae8)
- New language in README.md (9b5a627)
> Definitively fix emblem deletion, more housekeeping

- multiplayer_server/Player.php
- multiplayer_server/fns/announce_tournament.php
- multiplayer_server/rooms/ChatRoom.php
- Fixes server crashes when using /give, /a, /promote, /clear and any chat effects in levels.
- Doesn't give an error when using functions that a player doesn't have permission to use.
- Players/server owners can now check tournament status by using /t status, using `tournament_status()` in fns/announce_tournament.php
- Add emote :shrug:
- Add /promote for admins (same thing as /give, except the text is "bls1999 has promoted " instead of "bls1999 has given ")
- Update /help command
> Server crash fixes when using commands in levels, new commands/edits

- http_server/cron/fetch_folding_stats.php
The server can't award the parts if it doesn't know who got them!
I think this is all that needs to be done in the http_server/cron folder, although there could very well be needed changes in http_server/fns or even still cron.  Please check to make sure everything works.
> Fix folding awards

- http_server/www/login.php
Adds a sanity check to all logins that makes sure backticks aren't used in usernames.
Also uses an IP lookup API to determine the country code for player_deep_info.php.
> Add backtick check to login.php, fix country code

- multiplayer_server/Player.php
- multiplayer_server/fns/issue_tournament.php
Added game/chat room check and put in the variable `$player_room`.
Also cleaned up issue_tournament.php a bit.
The only issue I'm having is trying to figure out how to throw just the exception text I want to throw.  I have the `throw new Exception("text here!")` statements defined in /fns/issue_tournament.php. Then, I put the function in a `try{}` block and caught it in a `catch{}` block, both in Player.php.  When I was testing the stat error, I got this:
```
Error: Exception: Stat values can only be between 0 and 100. in /home/jiggmin/platform-racing-2-server/multiplayer_server/fns/issue_tournament.php:52
Stack trace:
#0 /home/jiggmin/platform-racing-2-server/multiplayer_server/Player.php(316): issue_tournament('/t none 1000 10...')
#1 …
```
> Optimize code, fix /t error and /clear crash

- http_server/fns/data_fns.php
- http_server/www/login.php
Remember me is now displaying the error for an invalid username.  This has to do with my check not accounting for token data.  I've added some new checks with the help of a new function (`is_empty()` in `data_fns.php`).
> Fix remember me login

- http_server/www/admin/part_ids.php
- http_server/www/login.php
- http_server/www/vault/vault_descriptions.php
- multiplayer_server/parts/Prizes.php
Optional thing because I'm weird: reverted a few names of stuff on prize pop-ups to their original pre-2014 ones. Most guides still call them these, so why not? *shrugs*
Edit: Added another commit to make the epic Jump Start Hat universal like the other campaign hats. (Right now it functions like a normal campaign prize; needs 4 players and only winner gets it.)
Edit 2: Added a few more.
> Update Prizes.php + Others

- http_server/www/message_send.php
Admins can now use `[url=https://example.com/]My Site![/url]` to link to things instead of needing to type out the long html tags.
> Make things easier for admins in message_send.php

- http_server/www/register_user.php
Users that contain #, %, and @ cannot be folded. I believe it's due to how folding at home stores usernames with those characters and this causes PR2 not to find a match with the usernames to be able to award the tokens and hats. 
Because of this I changed the allowed characters in usernames although % wasn't there so I'm not sure how to make it not allowed. Also 0 is allowed in usernames and technically the invalid character message tells you it is not.
> Fix future possible folding issues in register_user.php

- http_server/www/admin/update_guild.php
- http_server/www/guild_transfer.php
- http_server/www/remove_level.php
change `guild_transfer_select` to `guild_transfer_select_by_code`.
Also, it looks like I've already added the code for requester IP and confirmer IP to guild_transfer.php and confirm_guild_transfer.php.  Can you make this information available to admins by calling `guild_transfers_select_by_guild` in guild_deep_info.php?  This would make the information we see pretty much identical to the email change information.
> Fix update_guild.php after guild transfer merge

- http_server/www/admin/search_by_email.php
Allows admins to search for users by email address.  Hopefully in the future I'll figure out a way to grab the username from different email changes too.  That way, not only will we be able to search by the current email address, but we'll also be able to search by any address that has ever been associated with an account.
> Create email search tool for admins

- http_server/cron/fah_award_prizes.php
- http_server/www/admin/search_by_email.php
- http_server/www/admin/update_account.php
- http_server/www/bans/bans.php
- http_server/www/guild_join.php
- http_server/www/login.php
- http_server/www/player_search.php
- http_server/www/register_user.php
- multiplayer_server/Player.php
- multiplayer_server/fns/utils.php
- multiplayer_server/process/register_login.php
- multiplayer_server/rooms/Game.php
This pull is a bunch of small updates that have combined to form one normal-sized pull.
HTTP Server Fixes/Additions:
- A possible exploit where users could possibly log in as other users.  Fire-Bird was able to demonstrate something like this and I hope this fixes it (if it's not already fixed).
- An error where accounts missing pr2 data would break update_account.php
- An error where changing users' guild IDs in update_account.php would not increment the guild member count
- A parenthesis error in the ban log that lets people make huge queries to the database.
- An error that broke player_search.php
- A small fix in search_by_email.php
- HOPEFULLY fix F@H awards for good (the issue is that new folders aren't being made accounts in the fah database. I'm hoping that 53acfea will fix it, …
> Fixes/additions to http_server and multiplayer_server

- http_server/queries/get_info/pr2.php
- http_server/queries/get_info/user.php
- http_server/www/leaderboard.php
- http_server/www/mod/player_info.php
- multiplayer_server/HappyHour.php
- multiplayer_server/Player.php
- multiplayer_server/client/moderation.php
- multiplayer_server/fns/data_fns.php
- multiplayer_server/fns/promote_to_moderator.php
- multiplayer_server/fns/utils.php
- multiplayer_server/parts/Prizes.php
- multiplayer_server/rooms/Game.php
HTTP Server:
- Fixed query in queries/get_info/user.php
- Created query for pr2_select (check the code, commit 3e97cd5)
- Fixed player_info.php and semi-updated it to PDO
- Fixed server crash on admin server owner logout
- Fixed leaderboard.php
Socket Server:
- Made `name_to_player()` case insensitive and removed `name_to_id()` calls
- Fixed/optimized moderation.php, promote_to_moderator.php
- Disabled and removed +5 EXP bonus
- Added /hh command (see comments on 93c168a for more details) 
- Added a check for if the user is winning the artifact (see comments on 927f7f9). Hopefully it works?
There have been reports of botting on levels with a set prize with the +5 EXP bonus, and it's confirmed by those levels' play counts (see The Golden Compass and Hat Factory as examples).  Basically, …
> Botting patch, slight fixes

- http_server/www/admin/update_account.php
- http_server/www/leaderboard.php
- multiplayer_server/Player.php
- multiplayer_server/client/moderation.php
- multiplayer_server/fns/data_fns.php
Avoid future problems with empty part arrays by making sure each array has something in it before attempting to log out (`save_info()` in player.php or saving player data in update_account.php).  It's good to have validation for the part arrays just in case this happens again somewhere down the line.
Please make sure adding the check to `save_info()` will be better than adding it to `verify_parts()`.
Also included in this pull:
- Add /hh status to the members' /help command.
- Fix warnings (for some reason past me thought it would be a good idea to remove the code that actually administers a chat ban)
> Add part array validation on logout, fix warnings

- http_server/queries/changing_emails/changing_email_insert.php
- http_server/queries/changing_emails/changing_emails_select_by_user.php
- http_server/queries/guild_transfers/guild_transfers_select_by_guild.php
- http_server/queries/levels/levels_search.php
- http_server/queries/recent_logins/recent_logins_select.php
- http_server/queries/staff/actions/mod_action_insert.php
- http_server/queries/staff/ban_user.php
- http_server/queries/staff/bans/ban_user.php
- http_server/queries/staff/bans/throttle_bans.php
- http_server/queries/staff/level_unpublish.php
- http_server/queries/users/user_select_expanded.php
- http_server/www/account_confirm_email_change.php
- http_server/www/admin/guild_deep_info.php
- http_server/www/admin/player_deep_info.php
- http_server/www/admin/search_by_email.php
- http_server/www/admin/update_account.php
- http_server/www/ban_user.php
- http_server/www/mod/player_info.php
- http_server/www/player_search.php
Fixes:
- No change validation -> update_account.php
- Check for a non-existent guild when changing user into a new guild -> update_account.php
- Fix IP history -> player_deep_info.php
- Fix user_select_expanded
- Fix bans
- Fix level unpublishing (check my commit comments on cf8a7e7)
- Fix level searches (they were only searching by user)
- Revert curly braces
- Rearrange some functions and calls
- Fix random things broken in mod/player_info.php
- Display "none" on no guild in player search
Nice things:
- Admins now have some friendly links on guild_deep_info and player_deep_info
It sounds like a lot, but most of it was small changes in a few files.  One thing to note going forward: curly braces don't work the way you used them in 851c7bc, dadd592, and 7de6073.
Lastly, for the life of me, …
> Continue the PDOcalypse, fix a few things

- http_server/queries/campaign/campaign_select_by_id.php
- http_server/queries/guild_transfers/guild_transfer_complete.php
- http_server/queries/guilds/guild_increment_gp.php
- http_server/queries/guilds/guild_insert.php
- http_server/queries/guilds/guild_select.php
- http_server/queries/guilds/guild_select_active_member_count.php
- http_server/queries/guilds/guild_select_by_name.php
- http_server/queries/guilds/guilds_select_by_most_gp_today.php
- http_server/queries/levels/levels_search.php
- http_server/queries/messages/message_delete.php
- http_server/queries/messages/message_select.php
- http_server/queries/messages_reported/message_report_check_existing.php
- http_server/queries/messages_reported/messages_reported_check_existing.php
- http_server/queries/messages_reported/messages_reported_insert.php
- http_server/queries/recent_logins/recent_logins_select.php
- http_server/queries/tokens/token_delete.php
- http_server/queries/users/user_select_guest.php
- http_server/www/admin/guild_deep_info.php
- http_server/www/admin/player_deep_info.php
- http_server/www/admin/player_deep_logins.php
- http_server/www/admin/set_campaign.php
- http_server/www/ban_user.php
- http_server/www/guild_join.php
- http_server/www/login.php
- http_server/www/message_report.php
- http_server/www/mod/player_info.php
- http_server/www/player_search.php
- http_server/www/register_user.php
Fixes:
- HTML in assorted files
- Display of IP-only bans on player_info.php
- Message deletion, reporting (hopefully)
- Admins being able to ban mods
- Needlessly complicated syntax for `token_delete` (see note below)
- `campaign_select_by_id`
- Incrementing guild GP
- Some more curly braces
- Password-protected levels showing on title search
Addition:
- `admin/player_deep_logins.php` - Allow admins to see all recorded logins by a user, separated by pages.
I also updated #93, which sorely needed an update.
This pull originally included a change to the friends/ignored queries, but you went ahead and fixed those so it's kinda useless now.  I took care of the merge conflicts, so this should have no problem merging automatically.
`token_delete` note: please make sure b9f5c1e won't break …
> Fix assorted (many) errors

- http_server/cron/daily.php
- http_server/queries/changing_emails/changing_emails_expire_old.php
- http_server/queries/guild_transfers/guild_transfers_expire_old.php
- http_server/www/admin/player_deep_logins.php
- http_server/www/admin/set_campaign.php
- http_server/www/admin/update_account.php
- http_server/www/admin/update_guild.php
- http_server/www/ban_user.php
- http_server/www/guild_delete.php
- http_server/www/mod/archive_message.php
- http_server/www/mod/ban_edit.php
- http_server/www/mod/do_lift_ban.php
- http_server/www/remove_level.php
This update fixes action logging.  It also expires email change and guild transfer requests older than a day for security purposes.  Feel free to change the amount of time on that if you'd like, but I think that the least amount of time the changes are valid, the bigger a win for security.
> Fix action logging, expire old email change/guild transfer requests

- multiplayer_server/Player.php
- multiplayer_server/rooms/Game.php
Some small updates:
- Remove all references to Lux, as it's no longer used.
- Make the moon hat give double GP.
- Add the time in which a level was defeated to the chat message during tournament mode.
- Move some code in Player.php to let guests/users less than rank 3 use chat commands.
> Remove final references to Lux, repurpose Moon Hat

- http_server/www/admin/set_campaign.php
Enable referer check to prevent CSRF exploit that would allow to force change campaign.
> Enable referer check

- http_server/queries/users/users_select_top.php
- http_server/www/guild_search.php
- http_server/www/leaderboard.php
**Guild Search:**
This seemed to work on my localhost. It will hopefully have the same result here!
**Leaderboard:**
While debugging, I noticed that `users_select_top` was requiring `GROUP BY` to be present with the aggregate function `SUM()`.  When I grouped by `name`, it told me `pr2.rank` needed to be included since it was in the `SUM()` function.  It subsequently continued to tell me I needed more columns until I ended up with the monstrosity that is line 14.  From there, it seems to work okay in my test database, although I'm not sure if that's an effective method of fixing the problem. :thinking:
An alternative fix is to disable `ONLY_FULL_GROUP_BY` in the database to get rid of the `GROUP BY` line (14).  More info here: https://stackoverflow.com/questions/23921117/disable-only-full- …
> Actually fix leaderboard, guild search

- multiplayer_server/rooms/Game.php
This prevents socket commands other than `` chat` `` from being executed via the chat box. To take effect, this pull requires restarting all servers.
Thanks to @BrokenBulb78 for bringing this to my attention! \o/
> Prohibit backtick in race chats

- multiplayer_server/LocalBans.php
- multiplayer_server/Player.php
- multiplayer_server/client/moderation.php
- multiplayer_server/fns/demod.php
Currently, the only way to get rid of an accidental kick is to restart the entire server. This pull enables trial/permanent mods and server owners (no temps) to remove accidental kicks using the /unkick command.
Edit: This pull also includes a fix for admins trying to demote offline users displaying "Error: Could not find a user with that ID."
> Add /unkick for accidental kicks

- env.example.php
- http_server/www/login.php
I'm pretty sure that the only way I can let myself see guests' login data without letting everyone else see it is to simply allow the first bit of my IP address to see it and no one else.  I imagine this will definitively let me figure out if there is something different sent to the server to prohibit guest accounts from earning Kong badges, and in turn, fix it (if possible).  I'll send you the value for `$BLS_IP_PREFIX`.
> Add debugging for login.php

- http_server/fns/data_fns.php
Fix for exploit to bypass referer check (can be used to run member/moderator/admin actions without confirmation depending on targeted user privileges.)
> Fix referer check bypass exploit

- multiplayer_server/rooms/Game.php
Fixes the issue where the third decimal digit always displays as zero on scores being broadcasted to main with tournament mode on.
This should be fairly easy to move to lint, once ready.
> Fix tournament win times

- http_server/queries/guilds/guild_name_to_id.php
- http_server/www/guild_create.php
Right now, if you attempt to create a guild and it exists, you can't try again for another hour due to how the rate limiting is set up.  This pull checks if a guild name exists before adding to the rate limit and attempting to create a new guild, thereby fixing the issue.
> Check if guild exists before attempting to create

- http_server/fns/data_fns.php
- http_server/www/logout.php
Changed "!==" on strpos to "===" to correctly check is "ShockwaveFlash/" in the X-Requested-With header because "!==" was checking if it's not in string so this should fix the error when using this on logout.
Referer check wasn't needed there because it doesn't really have an use on this case.
> Change "!==" to "==="

- http_server/www/admin/restart_servers.php
Just in case.  We can already restart individual servers, so if we need to restart all of them, we can just use this script once per hour instead of typing the command in every server one-by-one.  Extra security by passing the token via POST instead of reading it in the cookie.
> Allow admins to restart all servers at once

- http_server/www/backups/backups.php
- http_server/www/hint.php
- http_server/www/style/pr2hub.css
**hint.php** - Added `require_once` for the `data_fns.php`. This missing line made the whole script break.
**backups.php** - Added the missing footer.
**pr2hub.css** - removed `.above_game_ad` CSS. It's useless since Jacob removed the ad from the page.
> Some fixes

- http_server/www/login.php
Since we can use the `require_trusted_ref` function, the old sitelock is useless, which can be bypassed anyway.
> Remove the old sitelock

- README.md
- http_server/www/login.php
- multiplayer_server/CourseBox.php
- multiplayer_server/Player.php
- multiplayer_server/fns/data_fns.php
- multiplayer_server/rooms/Game.php
This pull includes code that @famelegend1 wrote in #453 and #455, slightly modified.  A huge thank-you to him for inspiring the changes in ab19b37. :pray:
Socket Server:
- Check for rank 100 or above (except for Fred) on login in `Player.php`
- Check for rank 100 or above (except for Fred) when entering a race, d/c if above rank 100
- Check for a rank 100 or above when awarding opponent bonus EXP, and set to 0 if found
- Fix php warnings being sent to the console when `` loginFailure` `` is sent from `Player.php` (i.e. server full, rank 100 or above check on login)
- Fix a small bug that would crash the server if nothing was set for the hat, head, body, or feet values
HTTP Server:
- Check for rank 100 or above on login in `login.php`
README.md:
- Added @famelegend1
> Add various rank/exp sanity checks

- http_server/www/upload_level.php
The typecast to an integer at the introduction of the `$song` variable messed up the saving of a random song, because the client interprets an empty `song=` value as a random song and `song=0` as "None".  This pull makes it so the song string (song ID; what's passed in `$_POST['song']`) is only typecast to an integer right before adding to the database.
> Fix random song in levels

- common/manage_socket/check_servers.php
The CRON that controls this script will need to be updated to make sure that it's executing with `/http_server/cron/minute.php`. I'm currently in the process of reworking the structure of the repo with organipocalypse, so this is a temporary fix.
> Fix server restarts

- common/env.example.php
- common/queries/users/user_select_guest.php
- http_server/www/login.php
- multiplayer_server/fns/process_fns.php
I just reverted the guest login procedure to what it was before I attempted to fix the Kong badges.
Also, I added a line to `process_register_login()` in the socket server code that checks if the guest is online already. If so, it won't disconnect the guest that's online but it'll disconnect the person logging in. This way, people who know the guest password won't be able to troll others who are just visiting.
Edit: I also added a check for a direct guest account login in login.php.
> Fix guest logins

- http_server/www/place_artifact.php
- multiplayer_server/fns/artifact_fns.php
The artifact function's set first finder function isn't awarding prizes properly because it's looking for a false or null value instead of 0 for the first finder. This pull fixes that and tidies some other potential problem points as well.
> Fix automatic artifact prize awards

- http_server/fns/data_fns.php
- http_server/www/logout.php
Sometimes on logout, users will get an error saying they can only log out from the PR2 client. This check was originally put in place to prevent a CSRF exploit, but seeing as it creates false positives and fixes an issue that is non-destructive in the first place, I think it should be retired.
> Fix false positive

- common/queries/new_levels/check_newest.php
- common/queries/new_levels/delete_from_newest.php
- http_server/www/remove_level.php
- http_server/www/upload_level.php
We've had an issue in the past with level spam. As a fix, [Stxtics suggested](https://jiggmin2.com/forums/showthread.php?tid=851) that there be a limit to the number of levels that a user can publish to page 1 of newest at any given time. This pull adds that limit while still letting the user save their level.
Side note: I noticed that when a level gets unpublished, the level remains in `pr2_new_levels`. To make this pull work, I needed to count the number of levels from that table. I've added a function to `upload_level.php` and `remove_level.php` which delete the level from `pr2_new_levels` if it exists in that table.
> Limit publishing to newest

- multiplayer_server/Mutes.php
- multiplayer_server/PR2SocketServer.php
- multiplayer_server/Player.php
- multiplayer_server/ServerBans.php
- multiplayer_server/fns/client/moderation.php
- multiplayer_server/fns/data_fns.php
- multiplayer_server/fns/process_fns.php
- multiplayer_server/pr2.php
This pull separates chat bans from the player object in favor of a server-logging system (like how kicking works). The difference will be negligible to a normal player, but this will allow us to do a lot more with chat bans than before, as well as abolishing warn evading by logging out and back into an account with an active warning.
In the future, with regards to mutes/warnings, I hope to:
- Add a chat command that will allow a mod to mute a user for up to a day
- Add an unwarn chat command (the function is already in `fns/client/moderation.php`)
- Move all chat commands to a different php file so they aren't cluttering `Player.php`
This also fixes a bug with kicking where if a user attempts to log in using a different case as was previously used (i.e. JIGGMIN instead of Jiggmin), the …
> Convert warnings to mutes

- common/manage_socket/socket_manage_fns.php
- multiplayer_server/Player.php
- multiplayer_server/rooms/Game.php
The main focus of this pull is to tidy the output when it comes to logging things in server logs. This just makes messages easier to understand if you're trying to debug something that happened.
Technical details:
- restart_server: add sleep(1) between shutdown and start
- test_server: delegate to restart_server
- start_server: tidy code and log output
- shut_down_server: more accurate logging
- get_pid_file: tidy code
- read_pid: tidy code and log output
Also:
- Added admin name on server restart to the log (Player.php)
- Fixed a typo in Game.php (appyExpCurve -> applyExpCurve; sorry, couldn't resist)
With that, I believe every typo in the repo is gone. It was not an easy journey. We have come far since January.
> Improve server logging, tidy code

- common/queries/campaign/campaign_level_select_by_id.php
- http_server/www/delete_level.php
Before deleting a level, the server will check to see if the level is in a Campaign. If it is, it won't let the user delete the level.
This has happened before. While it's not a common thing (it's only happened about 1-5 times in PR2's history), I think it's probably best to have this check to save you the trouble of having to restore it if it happens. Just in case; especially with new Campaign levels every month from Campaign of the Month!
(I also can't test this without making tons of dummy levels on my localhost, so just take a gander and make sure everything looks up to par.)
Also, please run this query on the database:
```mysql
UPDATE `pr2_levels`
SET `live` = "1"
WHERE `level_id` = 1442589;
```
EDIT: To be clear, this protects against a level being deleted via the `delete_level.php` …
> Don't let campaign levels be deleted

- http_server/fns/pages/admin/contests/add_prize_fns.php
- http_server/fns/query_fns.php
- http_server/www/contests/award_prize.php
- http_server/www/login.php
- multiplayer_server/Player.php
- multiplayer_server/fns/vault_fns.php
- multiplayer_server/rooms/Game.php
Fixes:
- Fix guest login not working when returning from the level editor (#530)
- Stop 2 headers from appearing on an error in `/contests/award_prize.php`
- Add a header on success in `/admin/contests/add_prize.php`
- Fix fatal error when awarding prizes to accounts that don't have entries in `pr2`, `epic_upgrades`, or both* (a DB query is needed to complete this. see below)
Additions:
- Add a link to add another prize on success in `/contests/award_prize.php`
- Userify the HH deactivated message (socket server)
- Userify the perk activated messages (socket server)
- Add a tiny botting check, as discussed in [this comment](https://github.com/jacob-grahn/platform-racing-2-server/issues/285#issuecomment-417982001) (socket server)
*= run this query on the database (changes the default value …
> Small fixes/additions

- common/queries/users.php
- http_server/check_login.php
Guild ID no longer returns `null`
(last pull for now! sorry to spam you!)
> Quick check_login.php fix

- common/cron/daily.php
- common/cron/weekly.php
- common/multi_queries.php
- common/queries/bans.php
- common/queries/levels.php
- common/queries/tokens.php
- common/queries/user_delete.php
- common/queries/users.php
- functions/common_fns.php
- functions/cron/cron_fns.php
- functions/http_fns/http_data_fns.php
- functions/multi_fns/staff/promote_to_moderator.php
- http_server/admin/restart_servers.php
- http_server/admin/set_campaign.php
- http_server/delete_level.php
- http_server/guild_invite.php
- http_server/guild_leave.php
- http_server/login.php
- http_server/logout.php
- http_server/messages_get.php
- http_server/mod/ban_edit.php
- http_server/place_artifact.php
- http_server/vault/vault_finalize.php
- http_server/vault/vault_super_booster.php
- multiplayer_server/ChatMessage.php
- multiplayer_server/Player.php
- Setting the Campaign
- Level deletion (saving/loading works as intended in 152.3)
- Chat auto anti-spam filter
- Banning (and bans applying to users)
- Unpublishing levels
- Trial/perma mod detection
- PMs tab pages
- Ban edit mod logging (doesn't log the mod's IP address as yes/no)
- All server restarts
- Blank level listing pages (don't throw an error)
- Guild invitations/leaving
- Artifact placement
- Old account deletion (monthly cron task; find in weekly.php)
- Vault
- All of the level music is gone from PR2hub (404 error)
- Tournament server is down
- None of the Campaign levels have prizes (restore your last backup of the pr2_campaigns table and just rename it to campaigns)
- Please restore the recent_logins table. This will continue to help us do our jobs diligently [with IP …
> [URGENT] Misc. server fixes

- common/cron/hourly.php
- common/cron/minute.php
- common/cron/weekly.php
- common/queries/best_levels.php
- common/queries/part_awards.php
- functions/cron/cron_fns.php
- functions/http_fns/query_fns.php
- functions/multi_fns/client/lobby.php
- functions/multi_fns/process_fns.php
- http_server/admin/set_campaign.php
- http_server/login.php
- http_server/register_user.php
- http_server/vault/vault_finalize.php
- multiplayer_server/parts/Prizes.php
- multiplayer_server/rooms/Game.php
The query in the CRON was breaking campaign prizes updates, so I fixed it and made it update hourly instead of every minute (the campaign will never be changing that frequently). Additionally, admins can now manually update the campaign prizes with `/debug campaign refresh`, so there's no need for this.
Things that should also be quick:
- PR2 v153.1 is up at the client repo
- Please make a new permanent private server for guild id no. 205 (Beta Testers) so that I can start pushing betas to JV2 for testing
- Tournament server is down
- Random question: what is the title/artist of the original Baking Games intro song?
- ***Please run this query on the database to prevent errors:***
```mysql
ALTER TABLE pr2
CHANGE hat_array hat_array varchar(1000) NOT NULL DEFAULT '1',
CHANGE head_array …
```
> Unbreak campaign prizes, vault, fah

- functions/multi_fns/process_fns.php
We can switch ourselves into guilds anyway, so it makes sense that we should be able to enter any. Plus, the description of the private server specifies that _moderators_ will be unable to enter your private server.
> Let admins join private servers

- multiplayer_server/rooms/Game.php
Not sure why this wasn't a thing before now. I was testing something on my local machine and the next thing I know the whole server crashes because there were too few arguments passed to `sendChat`.
> allow systemChat in races

- multiplayer_server/pr2.php
Don't continue trying to start the socket server if the connection to the database fails.
> Catch exception on bad db connection

- multiplayer_server/rooms/Game.php
The message shouldn't show when the player is the last player in the game.
> Fix rogue dropped hat message

- multiplayer_server/parts/Parts.php
So I was browsing through this repository once upon a time and I saw that in the function "strToId" in Parts.php that with the Jump Start Hat, instead of having a bunch of "or" conditionals, it just searched through an array. Array $jump_start was declared beforehand to do this, and no such thing occurred with no other hat. So just today while looking through it again I thought "why not do it for all hats, might make it tidier?" So I did. I also added the string "arti" in the checks for the Artifact, 'cuz that's a very common shorthand for the hat.
Now I'm not sure if this is what you'd want. Maybe this is some ancient Jiggy code you didn't want to interfere with for prosperity's sake. Maybe the Jump Start hat must have an array declared when converting a string to its ID or else Fred …
> Tidy up strToId in Parts.php

- multiplayer_server/parts/Parts.php
- Moved the jump_start element to the start of the jumpstart hat's array and the top_hat element to the start of the top hat's array (this was because I was originally going to set the id with the 1st element of the array as upper case but then I realised I could just do it with the last element)
- Put all the arrays in 1 big array
- Made a foreach loop that goes through the array that checks whether the string is in each of the sub-arrays
- If it's in the sub-array, then the id is the last element of the sub-array
It didn't say anything was wrong in code checker for both versions 7.3 and 5.6 but I've never used php before so there's a good chance that something here is wrong
EDIT: IdToStr too
> Update to StrToId in Parts.php

- functions/http_fns/query_fns.php
- http_server/get_player_info.php
- multiplayer_server/Player.php
This pull:
- Fixes a bug with contest prize EXP awarding that would sometimes set the player's EXP points to the prize amount if they ranked up at least once in the process.
- Implements: https://jiggmin2.com/forums/showthread.php?tid=2998
Additionally, when rank tokens are enabled, the server will now use the player's base instead of active rank EXP progress for ranking and display. This means players won't have to decrease their rank tokens to rank up anymore and rank progress on popups/after races will use the player's base rank.
> Reform EXP gain w/ tokens

- http_server/upload_level.php
Levels now back up as their current version, not the one prior.
> Fix backup version bug
