server/parts/Feet.php

Added 34-39

---

server/pr2_moderation.php

Ban message:
- Added user-friendly times (lines 76-100)
- Temp mod bans now do not echo messages (line 112)
- Changed how the reason is displayed (lines 102-108, 114)
Promotions message:
- Re-added support for different messages for different promotions (lines 147-162)
- Fixed the dead link (lines 151, 156, 161)

Changed mechanics and messages

---

server/pr2_moderation.php

Line 181, changed "permanent" to "1000 years"

Typo fix on pr2_moderation.php

---

server/pr2_moderation.php

Last 2 small fixes for pr2_moderation.php

---

server/Player.php

Fixed <>&" from being converted to htmlspecialchars in regular messages, line 255
Added backtick check, lines 294-296
Added /t help, lines 297-308
Added /give, lines 339-355
Modified grammar with /pop, lines 356-369
Added /help, lines 375-387

Misc changes to player.php

---

http_server/www/mod/ban_edit.php
server/fns/promote_to_moderator.php

- No more error after promoting someone that's offline
- ban_edit.php checkboxes are fixed

Couple of fixes

---

README.md
http_server/www/login.php

When users logged in during New Years they received the Santa hat, this will give them the appropriate Party hat!

Hat awarding issue

---

http_server/www/index.html

Forgot to add the 2 :)

---

http_server/www/bans/show_record.php

Keep consistent with previous variables and not add new ones.
Patch in #43 works but it is a pretty roundabout way of doing it compared to how the previous variables are structured.

Add htmlspecialchars to $reason

---

http_server/www/api/award_part.php
http_server/www/api/calc_exp_points.php

@jacob-grahn 
Fix for XSS exploit (could be used to steal login tokens in some cases, that would allow logging in as targeted player without password by entering the token cookie to own browser.)

Fixed XSS exploit

---

http_server/www/guild_create.php

This code can prevent users from using illegal characters to disable other user accounts.

Fixed Guild Exploit

---

server/fns/artifact_first_check.php

This should make it so it only displays after a user has gotten the artifact first. Check my work, please.

Fixed artifact message

---

http_server/www/guild_create.php
http_server/www/guild_edit.php

For both files, I used `strlen(trim($guild_name)) === 0` on line 47.

check for only spaces in guild names

---

http_server/www/forgot_password.php
http_server/www/guilds_top.php

Just adding an html prevention to forgot password
Edit: added fix for HTML in guilds_top.php (will still give valid JSON but in text format instead of html)

Just an html prevention

---

http_server/www/login.php

Close your HTML tags, Jiggy!
(Also, typo fix)

Fix welcome PM

---

http_server/www/bans/show_record.php

Fixed ban editing and lifting by correcting the file paths in /bans/show_record.php.
Affected lines: 90, 92, 95, 114-115

Fix ban editing and lifting

---

http_server/fns/query_fns.php

Update banned popup

---

http_server/fns/output_fns.php

changed terms-of-use.php -> terms_of_use.php

Fix Terms of Use link in the footer

---

http_server/www/backups/index.php

Fix 403 Error at pr2hub.com/backups

---

http_server/cron/award_folding_prizes.php

Potential fix for #99.  Just uncommented the entirety of http_server/cron/award_folding_prizes.php.

[potentially] fix folding awards

---

multiplayer_server/fns/artifact_first_check.php

Although it made me laugh really hard, putting the artifact on the prize popup wasn't the BEST idea...
https://i.imgur.com/k22BJ4Z.png
This should fix it by making the head more visible.

Fixing artifact prize window, hopefully for the last time

---

multiplayer_server/pr2.php

This should fix tournament mode and prevent it from crashing the server and/or disconnecting the player.
Remember ya functions, Jiggy!

Fix tournament mode

---

http_server/www/ban_user.php
http_server/www/mod/ban_edit.php
http_server/www/mod/do_lift_ban.php
http_server/www/mod/guild_deep_info.php
http_server/www/mod/player_deep_info.php
http_server/www/mod/update_account.php
http_server/www/mod/update_guild.php
http_server/www/remove_level.php
multiplayer_server/fns/demod.php
multiplayer_server/fns/promote_to_moderator.php

Note on update_guild.php: the script says "error=A guild already exists with that name." when trying to update.  Since that was the specified error text, I can't really trust that that is the real error. I would assume the issue stems from the `$db->call` function not being able to handle the extra arguments.
Have a look and see what you can find.  d1a4950

Fixes for mod navs, action log, admin tools

---

http_server/www/mod/update_guild.php
multiplayer_server/fns/promote_to_moderator.php

See individual commits for more information.

Fixes to action log/update_guild.php

---

http_server/www/message_report.php

I broke it :(
This fixes it :)

Fix message reporting

---

http_server/www/message_report.php

Per Jiggy's suggestion in #127

Hopefully actually fix message_report.php

---

http_server/www/player_search.php

I just coded a Player Search page for PR2Hub! ^^
Tell me if there are possible exploits! :3
Image ( --Player Search-- ): https://i.imgur.com/AOnVhk9.png

Player Search Page for PR2Hub

---

http_server/www/mod/action_log.php
multiplayer_server/Player.php
multiplayer_server/fns/issue_tournament.php
multiplayer_server/parts/Hats.php

I usually get it on the second try.
- Cleaned up and reworked the dynamics for issue_tournament.php
- Actually possibly maybe fixed server crashes (see commit 6111c4a for more info)

Actually fix server crashes

---

http_server/www/player_search.php

Added one more `<br />`, also @jacob-grahn please upload the image (-- Player Seach --) to PR2Hub
https://i.imgur.com/AOnVhk9.png

A very little fix at player_search.php

---

http_server/www/admin/guild_deep_info.php
http_server/www/admin/player_deep_info.php
http_server/www/admin/set_campaign.php
http_server/www/admin/update_account.php
http_server/www/admin/update_guild.php
http_server/www/mod/mod_log.php

mod_log.php was missing a semicolon that was killing the entire script, so I went ahead and fixed that.
Each commit has specific changes, but in summary: I fixed a bunch of stuff.
I'm going to edit set_campaign.php to accept arguments for custom prize lists as well.  In the end, though, I need you to enable the database to accept a request to set the campaign.  Or, now that I think about it, would the database function from the old Campaign of the Fortnight setter still work?  If so, could you send me the code for that?  Thanks!

Fixes to /admin directory, mod_log.php

---

http_server/www/guild_delete.php

Replaced broken variables from the copy/paste.

Fix action logging in guild_delete.php

---

http_server/fns/data_fns.php
http_server/www/admin/guild_deep_info.php
http_server/www/admin/update_account.php
http_server/www/admin/update_guild.php
http_server/www/ban_user.php
http_server/www/message_report.php
http_server/www/mod/ban.php
http_server/www/mod/ban_edit.php
multiplayer_server/fns/demod.php
multiplayer_server/fns/promote_to_moderator.php

- Hopefully finally fix PM reporting
- Fix action logging in a bunch of files
- Some cosmetic edits and housekeeping
- Added two new functions (`is_empty()` and `check_value()`; you can see what they do in 7e4ddd1)

Fixes to PM reporting, admin tools, new functions in data_fns.php

---

multiplayer_server/Player.php

This is another completely optional pull.
I've been a long-time supporter of staff being able to restart servers since they've been known to be wonky every now and then.  If you don't want to give admins that power, that's totally fine and I completely understand; However, if you aren't vehemently opposed to the idea, I believe it would be a good resource for admins.
The process is simple: admin types `/restart_server` and gets prompted with a big scary message that looks like this:
```
WARNING: You just typed the server restart command. If you choose to proceed, this action will disconnect EVERY player on this server. Are you sure you want to disconnect ALL players and restart the server? If so, type: /restart_server yes, i am sure!
```
Then, if the admin types `/restart_server yes, i am …

Allow admins to restart a PR2 server

---

http_server/www/admin/admin_log.php
http_server/www/admin/part_ids.php
http_server/www/admin/update_account.php
http_server/www/admin/update_guild.php
http_server/www/guild_delete.php
http_server/www/hint.php
http_server/www/message_report.php
http_server/www/mod/ban_edit.php
http_server/www/mod/do_lift_ban.php
http_server/www/vault/vault_descriptions.php
multiplayer_server/Player.php
multiplayer_server/fns/demod.php
multiplayer_server/fns/promote_to_moderator.php

- Slight fixes to ban_edit.php, do_lift_ban.php, admin tools
- Fixing promote_to_moderator.php/demod.php/guild_delete.php action logging
- Remove referrer check in admin/part_ids.php and admin_log.php
- Add debugging code to figure out what the heckin problem is for server restarts and message reports.
- A couple of cosmetic fixes to fns/promote_to_moderator.php and vault/vault_descriptions.php
- Fixed hint.php
My bad.

Fixes my mistakes, adds debugging code

---

http_server/www/login.php

Temporary change.  Trying to debug ongoing issues with remember me.

Add debugging to login.php

---

http_server/fns/data_fns.php
http_server/www/login.php

`find()` was overwriting itself.

Fix remember me

---

http_server/www/hint.php
http_server/www/staff.php
http_server/www/style/hint.css
http_server/www/style/pr2hub.css

This is the correct one, merge that, it has function inside and I fixed a typo :p @jacob-grahn

Create staff.php | finally the correct one :p

---

http_server/www/forgot_password.php
multiplayer_server/HappyHour.php

Fix for the exploit https://github.com/Myst1cZ/Pr2MailCSRF

Fix for Pr2MailCSRF

---

http_server/www/vault/vault_descriptions.php
multiplayer_server/parts/Prizes.php

I think the game thought "true" was a description, oops. That or it just hates custom campaigns.

Really fix the epic Jump Start Hat

---

http_server/www/hint.php
http_server/www/player_search.php
http_server/www/staff.php

Fix the broken columns
Also adds a link to the staff list on player_search.php if the user is a mod or more

staff.php fixes

---

http_server/www/account_change_email.php
http_server/www/account_confirm_email_change.php
http_server/www/admin/set_campaign.php
http_server/www/message_report.php
multiplayer_server/Player.php
multiplayer_server/fns/demod.php
multiplayer_server/fns/promote_to_moderator.php
multiplayer_server/pr2.php

There seems to be an issue retrieving some variable or accessing the shutdown_server() function in the /restart_server command.  This adds some debugging code to make sure we can figure out exactly what is causing this error.
This should also fix the /timeleft command, and the confirmation/error messages for successful temp mod promotions and unsuccessful demotions.

Add/fix debugging, other misc fixes/changes

---

http_server/www/account_change_email.php
http_server/www/player_search.php
http_server/www/staff.php

If you view a staff member using player_search.php it currently looks like this. https://i.imgur.com/1CuUEjV.png

Add missing new line in player_search.php and fix staff.php

---

multiplayer_server/HappyHour.php

This SHOULD disable HH on servers with tournament mode enabled... but do check my code to make sure it works.

Disable HH on tournament, formatting in HappyHour.php

---

http_server/cron/fah_award_prizes.php

Use
`$db->call('message_insert', array($user_id, 1, $message, '0'));`
Instead of 
`send_message()`

Hopefully fix the F@H PM

---

http_server/www/account_change_email.php
http_server/www/message_report.php
multiplayer_server/fns/demod.php
multiplayer_server/fns/promote_to_moderator.php

- Fix message reporting
- Fix demod.php bug
- Fix admins being able to promote other admins

Fix message reporting, bugs

---

http_server/www/message_report.php

I'm REALLY tired of this file.

ACTUALLY fix message reporting

---

multiplayer_server/fns/promote_to_moderator.php

I may have accidentally demoted you to a moderator in the process of testing this, @jacob-grahn :fearful: 
https://i.imgur.com/IefZd0B.png
https://i.imgur.com/P8E1wWM.png

actually fix admins promoting other admins

---

http_server/www/admin/update_guild.php

Fix guild_transfer_insert in update_guild.php

---

http_server/www/admin/search_by_email.php

it would help to add `$row = $result->fetch_object();`

hopefully fix search_by_email.php

---

http_server/www/ban_user.php
http_server/www/bans/show_record.php
http_server/www/change_password.php
http_server/www/delete_level.php
http_server/www/forgot_password.php
http_server/www/message_report.php
http_server/www/mod/archive_message.php
http_server/www/mod/ban_edit.php
http_server/www/mod/do_lift_ban.php
http_server/www/mod/lift_ban.php
http_server/www/mod/player_info.php
http_server/www/mod/reported_messages.php
http_server/www/submit_rating.php

Seems like the server had a vehement opposition to `mysqli_real_escape_string`, so `addslashes` is making its return until I have a chance to convert everything to prepared statements.
Before I convert things to prepared statements, some things I need from you:
- What queries the db procedures execute when called
- Verify that `$mysqli->prepare` and other prepared statement functions will work on this server
- Fix `mysqli_real_escape_string` or tell me what I did wrong (lol)
**PLEASE PLEASE PLEASE check my changes and make sure it doesn't open an opportunity for SQL injection.**

Fix bugs from pull #228

---

multiplayer_server/Player.php

This is useful because anyone can modify the client and increase the max character value.

Added 100 character check in Player.php

---

http_server/www/guild_create.php
http_server/www/guild_edit.php
http_server/www/register_user.php

When registering an account the list of allowed characters does not match the characters which are actually allowed. I've fixed this and made a slight change to the error message returned when an illegal character is used.

 Update register_user.php and guild_create.php

---

multiplayer_server/Player.php

Adds the /dc and /kick commands for trial/permanent moderators.  Also fixes some code dynamics.

Add /dc, /kick, rework code in Player.php

---

http_server/www/player_search.php

Fixed Error when loading the page and fixed double form when searching a user.

Small fix in player_search.php

---

multiplayer_server/Player.php
multiplayer_server/rooms/Game.php

1 dot. Oy vey.
Also, the artifact bonus is now a maximum of 50k, but the rank where it reaches 50k is rank 60 instead of 20.

Fix server crash, change artifact bonus

---

http_server/www/leaderboard.php
multiplayer_server/HappyHour.php
multiplayer_server/rooms/Game.php

Apparently the server crashes if you already have the prize that's being offered.  I'm hoping this fixes it.
Also, fix a variable in leaderboard.php and fix the time display in `HappyHour::timeLeft()`

Hopefully fix server crash on already having prize

---

http_server/queries/campaign/campaign_select_by_id.php
http_server/queries/guild_transfers/guild_transfers_select_by_guild.php
http_server/queries/guilds/guild_select_members.php
http_server/www/admin/guild_deep_info.php
http_server/www/admin/player_deep_info.php

I've been finding a few queries with `p_` before some of the variables.  I assume this has to do with stored procedures?  I've been converting them as I find them to PDO values.
Also, if you could post the error log for /admin I'd be a very happy man.
Finally, what is the query for `user_select_expanded`?

Fixes to admin tools, PDO queries

---

http_server/queries/levels/levels_search.php
http_server/queries/levels/levels_select_by_owner.php

Someone was feeling a little reckless and switched level search by title/user 😂 @jacob-grahn

Fix level search

---

http_server/queries/recent_logins/recent_logins_count_by_user.php
http_server/queries/users/user_insert.php
http_server/queries/users_new/users_new_insert.php
http_server/www/admin/player_deep_logins.php
http_server/www/messages_get.php
http_server/www/register_user.php

Looks like the issue with the messages was it was pushing the raw database result as the return data of messages_get.php.  Hopefully changing the variable will fix this (foreach may be doing weird things to the variable scope).

Fix player_deep_logins.php, messages_get.php

---

http_server/fns/query_fns.php
http_server/queries/users/user_select_full_by_name.php

When you login first time you will be seen as a guest due to not loading all of their user data etc

Fixed pass_login missing user data

---

http_server/queries/guilds/guild_increment_member.php
http_server/queries/staff/admin/admin_account_update.php
http_server/queries/users/id_to_name.php
http_server/queries/users/users_select_top.php
http_server/www/remove_level.php
http_server/www/upload_level.php

Theoretically, this will:
- Fix guild member incrementing
- Fix account updating for the admins
- Be a solution to our `active_rank` problem in `users_select_top.php`

Fixes to guilds, admin tools, id_to_name, misc

---

multiplayer_server/Player.php
multiplayer_server/loadup.php
multiplayer_server/process/register_login.php
multiplayer_server/rooms/ChatRoom.php

- Server owners are now server admins and can promote temp mods on their server
- Testing the new `become_guest()` function I added to Player.php for badges support on Kong (only one account is enabled to use this function on login)
- Make HH on server restart 30 mins and a 1/10 chance of occurring
- Add /rules command and change the welcome message for main chat to include the rules link

Make server owners admins on their server, add become_guest()

---

multiplayer_server/fns/pdo_connect.php

Add pdo_connect.php to multiplayer_server/fns

---

http_server/queries/guilds/guild_update.php
http_server/www/admin/set_campaign.php
http_server/www/admin/update_account.php
http_server/www/ban_user.php
http_server/www/bans/show_record.php
http_server/www/guild_delete.php
http_server/www/mod/ban_edit.php
http_server/www/remove_level.php

Fix action logging, ban_edit.php, set_campaign.php

---

multiplayer_server/client/moderation.php
multiplayer_server/process/register_login.php

It seems that logging into a guest account with a password (email me if you're interested how I do this) yields different results than clicking "Play As Guest".  I need to perform some more tests.

More tests for become_guest()

---

http_server/queries/contest_winners/contest_winner_insert.php

Forgot one thing.  Can you add this column to the db?  `varchar(15)` should suffice.

[Tiny pull] Add host_ip to contest_winner_insert

---

multiplayer_server/Player.php
multiplayer_server/fns/artifact_first_check.php
multiplayer_server/fns/demod.php
multiplayer_server/fns/promote_to_moderator.php
multiplayer_server/fns/server_owner.php

I may have accidentally demoted you in the process of testing your code that prevents admins from demoting other admins. :sos:

Some multiplayer_server fixes

---

http_server/queries/changing_emails/changing_emails_expire_old.php
http_server/queries/guild_transfers/guild_transfers_expire_old.php
http_server/www/mod/ban_edit.php
http_server/www/upload_level.php

Unfortunately, gonna need you to roll back the `guild_transfers` and `changing_emails` tables. Sorry :/
If it's possible, could you also keep the most recent guild transfer/email change logs?  I would guess there are only a handful, which can be easily entered into the db, albeit manually if need be.  If it's too much work, don't worry; it would just be useful information to have. :man_shrugging: 
Again, really sorry. Forgot my `AND status = "pending"` :/

Some http_server fixes

---

http_server/www/guild_kick.php

fix kicker appearing as kickee in message

---

http_server/www/admin/update_account.php
multiplayer_server/Player.php
multiplayer_server/client/lobby.php

In keeping with the theme of this pull (#333), there are three commits and three files changed in this pull:
- Fix changing usernames to a different case and guild incrementing in manual guild changes in update_account
- Don't let Fred enter the admin room
- Fix a broken variable in Player.php

Three small fixes

---

multiplayer_server/loadup.php

restarting all servers is required for this to work

fred server only for artifact

---

multiplayer_server/rooms/Game.php

sorry, requires another all-servers restart :s

one more check for fred server

---

http_server/www/login.php

don't need this since it's checked in pass_login

fix double ip check

---

multiplayer_server/CourseBox.php
multiplayer_server/rooms/Game.php

Partly because I'm annoyed by the malicious pulls. These checks would prevent the tricks used by those bots from being exploited, even if they succeed.

Anti-botting safety checks

---

http_server/fns/query_fns.php
http_server/queries/best_levels/best_levels_monthly.php
http_server/queries/contest_prizes/contest_prize_select.php
http_server/queries/contest_prizes/contest_prize_select_id.php
http_server/queries/contest_prizes/contest_prizes_select_by_contest.php
http_server/queries/contests/contest_select.php
http_server/queries/contests/contests_select_by_winner.php
http_server/queries/users/user_select_power.php
http_server/queries/users/users_select_top.php
http_server/www/admin/contests/add_contest.php
http_server/www/admin/contests/edit_contest.php
http_server/www/contests/award_prize.php
http_server/www/contests/contests.php
http_server/www/contests/view_winners.php
http_server/www/login.php
http_server/www/message_report.php
http_server/www/mod/ban_edit.php
http_server/www/mod/do_lift_ban.php
http_server/www/style/pr2hub.css
multiplayer_server/Player.php
multiplayer_server/parts/Prizes.php
multiplayer_server/rooms/Game.php

HTTP Server:
- Debugging round 2, here I come! (contests)
- Fix remember me
- Fix leaderboard
- Fix message reporting
- Fix ban editing
- Restore date to ban lifting reasons
- Hopefully fix ATB levels being really random (requires running monthly cron job)
- I think this will FINALLY fix kong badges (see a849df1 for more info)
Socket Server:
- Don't let Fred promote/demote server mods (temps)
- Update GP calculations for multiple moon hats
- Improve time display on the tournament server
- Add new constants for general code optimization
- Update description of moon hat in Prizes.php (probably will not be used since flavor text doesn't show on the client anymore)

Fix errors with contest hub, other things

---

http_server/fns/query_fns.php
http_server/queries/contest_prizes/contest_prize_select.php
http_server/queries/contest_winners/contest_winner_insert.php
http_server/queries/contest_winners/contest_winners_select_all.php
http_server/queries/contest_winners/contest_winners_select_by_contest.php
http_server/queries/contest_winners/throttle_awards.php
http_server/queries/contests/contests_select.php
http_server/queries/epic_upgrades/epic_upgrades_update_field.php
http_server/queries/pr2/pr2_update_part_array.php
http_server/www/admin/contests/add_contest.php
http_server/www/admin/contests/add_prize.php
http_server/www/admin/contests/edit_contest.php
http_server/www/admin/contests/remove_prize.php
http_server/www/contests/award_prize.php
http_server/www/contests/contests.php
http_server/www/contests/view_winners.php
http_server/www/style/pr2hub.css

I was having trouble trying to figure out how I'd even start to go about debugging these scripts.  Then I remembered that the DB queries are public, so I created a few tables in a database on my localhost in order to mimic the PR2 server DB's structure for proper testing.  I have good ideas sometimes.
Anyway, this all worked on my localhost so it should theoretically work on PR2's server.  Please add a column to `contest_winners` (as outlined in #370) before merging.
I'll fix those pesky IP searches next. :roll_eyes: :joy:

Fix Contests Hub (last pull about this???)

---

http_server/www/rules/index.php

https://jiggmin2.com/forums/showthread.php?tid=385 -> pr2hub.com/rules

Create shortened rules link

---

http_server/www/login.php

HttpOnly for extra cookie security.

Add HttpOnly to token cookie

---

http_server/queries/staff/admin/users_count_from_ip_expanded.php
http_server/queries/staff/admin/users_select_by_ip_expanded.php
http_server/queries/users/users_select_by_ip.php
http_server/www/admin/ip_deep_search.php
http_server/www/mod/ip_info.php

Fix mod/admin IP searching

---

README.md
http_server/fns/data_fns.php
http_server/fns/query_fns.php

Just so the ban message won't have html code.

Add htmlspecialchars to ban reason

---

multiplayer_server/Player.php
multiplayer_server/client/moderation.php
multiplayer_server/rooms/ChatRoom.php
multiplayer_server/rooms/Game.php

Also, check if kicked before performing /unkick.

Update rules link to shorter one on the servers

---

http_server/www/guild_search.php

Changes I made:
- Always output the header so we don't need to call that function many times.
- Not throwing "No guild name or id." when someone is loading the page.
- Removed the center tags, the function does that already.

One last change in guild_search.php

---

multiplayer_server/rooms/Game.php

I threw everything in a try/catch and added a new `foreach`, using `$this->player_array as $player` before calling `$player->socket->write()`. Hopefully that fixes things.

Changes to the in-race chat (don't crash server)

---

http_server/www/mod/player_info.php

Prevent the script from blowing up if the player doesn't have an entry in the PR2 table.

Slight fix for /mod/player_info.php

---

http_server/www/logout.php

Fix for the exploit https://github.com/Dex472/TokenEater

Fix for TokenEater force logout exploit

---

http_server/cron/artifact_hint.php

Just an additional bit of information to be output to artifact_hint.php

Add updated_time to artifact_hint.txt output

---

http_server/www/random_level.php

Fix random_level.php

---

http_server/www/account_change_email.php
http_server/www/forgot_password.php
http_server/www/register_user.php

This pull provides much-needed security updates by sanitizing the email inputs to `forgot_password.php`, `account_change_email.php`, and `register_user.php`.

Sanitize email inputs

---

http_server/queries/contest_winners/throttle_awards.php

`INTERVAL 6 DAYS` -> `INTERVAL 6 DAY`
really sql

fix throttle_awards

---

http_server/www/guild_search.php

- Members now display their individual GP stats rather than the guild's GP stats
- Center everything

Fixes to Guild Search

---

http_server/www/admin/set_campaign_fns.php
http_server/www/admin/update_account.php
http_server/www/admin/update_guild.php
http_server/www/backups/backups.php
http_server/www/contests/award_prize.php
http_server/www/contests/contests.php
http_server/www/guild_transfer.php
http_server/www/hint.php
http_server/www/login.php
http_server/www/logout.php
http_server/www/server_status.php
http_server/www/staff.php
http_server/www/submit_rating.php

This pull is more about continuity within the code than anything else.  I got rid of some weird formatting in error messages, [like this](https://images-ext-1.discordapp.net/external/FolDKiyc7hc19LgQvv0USrnNCHYPBeZzVOvLkLaJMmo/https/image.prntscr.com/image/cmPhYZGpSPeAIzii1HoNPg.png).

Formatting

---

http_server/www/logout.php

It's throwing an error every time someone logs out.

Revert is_from_game fix in logout.php

---

http_server/www/contests/award_prize.php
http_server/www/contests/contests.php

Final contests hub changes!!!

---

multiplayer_server/Player.php

- Add `:thinking:` and `:lol:` (as well as aliases for the two)
- Make the emotes case-insensitive (i.e. replace the text regardless of `:shrug:` or `:SHRUG:`)
- Add `/emotes`, which explains the syntax for the different emoticons.
Unicode has evolved, and as a result, emojis are available on more devices than ever before.  I googled how to put unicode characters into a php file, and it just said to paste them straight in. 🤷‍♂️

Changes to text emotes

---

http_server/cron/hourly.php
http_server/queries/part_awards/ensure_awards.php
http_server/queries/part_awards/part_awards_select_list.php

I figured since the script needed fixing anyway, it would make sense just to add it to the hourly cron while we're at it. 🤷‍♂️

Convert ensure_awards to fn, add to hourly cron

---

http_server/fns/data_fns.php
http_server/queries/users/user_select_mod.php
http_server/www/admin/contests/add_prize.php
http_server/www/admin/contests/remove_prize.php
http_server/www/mod/player_info.php
multiplayer_server/PR2Client.php
multiplayer_server/fns/shutdown_server.php
multiplayer_server/manage/shut_down_all.php
multiplayer_server/pr2.php
multiplayer_server/process/shut_down.php

A bunch of small updates that fix a bunch of small things.  I also improved some of the outputs from the socket server.  Take a look and see if things look good; I tested it all locally, so it should work.

Housekeeping

---

http_server/www/login.php

refer to comment in bls's last pull. this should fix the stated problem there.

Rank Token Sanity Check

---

http_server/fns/send_pm.php
http_server/www/add_friend.php
http_server/www/delete_level.php
http_server/www/emblem_upload.php
http_server/www/forgot_password.php
http_server/www/get_levels.php
http_server/www/get_user_list.php
http_server/www/guild_create.php
http_server/www/guild_edit.php
http_server/www/guild_invite.php
http_server/www/guild_join.php
http_server/www/guild_kick.php
http_server/www/guild_message.php
http_server/www/ignore_user.php
http_server/www/message_delete.php
http_server/www/message_report.php
http_server/www/messages_delete_all.php
http_server/www/messages_get.php
http_server/www/remove_friend.php
http_server/www/un_ignore_user.php
http_server/www/upload_level.php

When I end up submitting another pull to test a new fix for Kong badges, these things will need to be disabled so that guests don't have access to all the member-only stuff.

Guest checks for assorted files in the http_server

---

multiplayer_server/rooms/Game.php

quickly merge this pls

---

http_server/www/bans/view_priors.php

This script will allow members to view their priors.
Thanks to @bls1999 for helping me to fix my broken script! ❤️

view_priors.php

---

http_server/www/account_change_email.php
http_server/www/mod/player_info.php

Some things broke in player_info.php after adding the GET parameter `name` to `/mod/player_info.php`.  This update fixes those broken things.
Also, a variable was misnamed in `account_change_email.php`. That has been fixed as well.

Fixes to player_info.php and account_change_email.php

---

README.md

should clarify some stuff. also bls i fixed a little recurring capitalization error of yours :)

some important stuff to put on guidelines

---

common/cron/minute.php

I made a boo-boo and left in some commented code from debugging.
In other news, the repo is now at #500!

Uncomment necessary operations in minute.php

---

multiplayer_server/HappyHour.php

Fix for /hh status when triggered by random_hour

---

http_server/www/contests/contests.php

add missing footer in contests hub

---

multiplayer_server/Player.php

The old code I had here didn't do what I set out to accomplish it doing. Adding a `foreach` block to the existing `if` block seems to have done the trick.

Fix server crash on part overflow

---

http_server/fns/cron/fah_fns.php

Oh, you know. Folding at Home decided to update their fast teampage URL for the first time since PR2 came out, so it broke yet again.
I'd like to be able to go a year without this breaking, even if it's not my fault in the first place. That would be nice.

Fix FAH pt. 79

---

multiplayer_server/Player.php

This command will output helpful links

Add guides command

---

config.php
http_server/www/login.php
http_server/www/place_artifact.php
multiplayer_server/Player.php
multiplayer_server/fns/client/lobby.php
multiplayer_server/fns/staff/server_owner.php
multiplayer_server/loadup.php

2 changes:
- Logs special staff account logins that wouldn't normally appear on the mod action log (Fred/Sir/Clint).
- Changes Fred's ID to a constant in all instances of use, puts the constant in config.php

Log special staff account logins

---

multiplayer_server/CourseBox.php

Forgot to remove a class constant reference to Fred after making him a global constant. My bad.

[Quick Merge] Fix server crash on level entry as Fred

---

http_server/www/ignore_user.php

Join us next time on "Things that don't make sense in PR2"!
(This was a pseudo-request made on [JV2](https://jiggmin2.com/forums/showthread.php?tid=1160&pid=12337#pid12337))

Don't let users ignore themselves

---

multiplayer_server/Player.php
multiplayer_server/RaceStats.php
multiplayer_server/fns/artifact_fns.php
multiplayer_server/rooms/Game.php

- Temps no longer get muted
- Artifact no longer awards the EXP if the player quits before all finishes are bumped
- Unmute command added (function already existed in moderation.php)
I think one of these days I'm going to start on Organipocalypse pt. 4. Weeeeee

Small mute, arty w/ obj mode fixes

---

http_server/www/guild_search.php

Display correct GP values in guild_search.php

---

config.php

oof. config.php is kiiiiiinda important...

forgot a file! sorry!

---

common/queries/users.php
functions/http_fns/pages/contests/part_vars.php
functions/http_fns/query_fns.php
functions/multi_fns/client/moderation.php
functions/multi_fns/multi_data_fns.php
http_server/admin/part_ids.php
http_server/guild_transfer.php
http_server/level_pass_check.php
http_server/login.php
http_server/register_user.php
http_server/upload_level.php
multiplayer_server/ChatMessage.php
multiplayer_server/parts/Parts.php
multiplayer_server/parts/Prizes.php

This *should* be the last of the changes. Keep in mind, these things still require your attention @jacob-grahn:
- PR2 v153 is up at the client repo
- For some reason, Campaign data isn't making it from the database to the servers' global `$campaign_array` variable; therefore, prizes are unable to be won.
- Tournament server is down
- The vault isn't working
- The email issue with hotmail/live email addresses is still a thing (the email I sent you with the subject "URGENT: Emails undeliverable to hotmail/outlook/live addresses"
- Please make a new permanent private server for guild id no. 205 (Beta Testers) so that I can start pushing betas to JV2 for testing
- Please run this query on the database (future PR2 sets smile upon you):
```mysql
ALTER TABLE pr2
CHANGE hat_array hat_array …
```

[URGENT] Fix account creation, level passwords

---

functions/http_fns/pages/vault/kong_order_placed.php
http_server/vault/kong.php
http_server/vault/vault_finalize.php

really did not want to have to do this. soooooo ready for my alt's PMs to be spammed!!! :/

super mega vault debugging

---

functions/http_fns/pages/vault/kong_order_placed.php
http_server/vault/kong.php
http_server/vault/vault_finalize.php

vault debugging -- let's try this

---

functions/http_fns/pages/vault/kong_order_placed.php
http_server/vault/vault_finalize.php

remove debugging, re-enable vault

---

multiplayer_server/ChatMessage.php

I cannot believe that you changed it on one thing but not the other. I am very disappointed in you and because of this, I'm removing your bird set on PR2. I hope this is a lesson learned and it won't happen again. I expect a 500-word minimum letter from you explaining how sorry you are and some proof that this will not happen again, thanks. 
-Stxtics

you forgot to change shrug on /emotes

---

common/queries/servers.php
functions/http_fns/http_data_fns.php
http_server/admin/management/db_query.php
http_server/admin/management/multi_logs.php
http_server/admin/management/phpinfo.php
http_server/admin/management/view_error_log.php

Sent you an email @jacob-grahn

Admin management folder

---

multiplayer_server/ChatMessage.php

Emotes work in races

---

http_server/download.txt
http_server/login.php
http_server/version.txt

Version Update

---

http_server/login.php

let admins log into private servers pt. 2

do the thing here too

---

http_server/download.txt
http_server/login.php
http_server/version.txt

version 153.2

---

common/cron/update-s3-version.php
http_server/index.php

- Auto update the version file on amazon s3. This should keep older versions of the loader working as new clients are released.
- Update swf url on pr2hub.com.

auto update the version on s3

---

common/queries/contest_winners.php
common/queries/user_delete.php

Contest things

---

functions/multi_fns/artifact_fns.php
multiplayer_server/Player.php

Require people finding the artifact first to have the following account requirements:
- Rank 30 or higher
- Be registered for 3 months or more

Artifact Changes

---

http_server/get_player_info_2.php

april fools :)

---

http_server/mod/ban.php

Add `htmlspecialchars` to a place where it is _definitely_ needed.

Patch broken ban mechanic

---

common/queries/artifacts_found.php
multiplayer_server/rooms/Game.php

- Don't show "Artifact Found!" if 0 EXP was gained
- Fix artifact awarding EXP

Artifact fixes

---

functions/http_fns/pages/vault/vault_fns.php
http_server/vault/vault.php
multiplayer_server/Player.php
multiplayer_server/rooms/Game.php

- x2 EXP multiplier (in addition to any bonuses from HH, hats, campaign, etc)
- 25% off vault purchases

Anniversary 2019

---

functions/http_fns/pages/vault/vault_fns.php
multiplayer_server/Player.php
multiplayer_server/rooms/Game.php

You see, the anniversary celebration doesn't really work if you don't restart the servers to apply the changes...

Extend anniversary benefits through May 5

---

http_server/account_change_email.php
http_server/forgot_password.php
http_server/guild_transfer.php

I'm hoping this fixes the email issue plaguing users with outlook, hotmail, and live email addresses.

Change global "from" email

---

multiplayer_server/ChatMessage.php

I added the artifact guide under /guides to help new users know about the artifact hat.

Adding Artifact Guide

---

functions/http_fns/pages/vault/vault_fns.php
http_server/vault/vault.php
multiplayer_server/Player.php

Summer sale

---

README.md

Updating it because i deleted that account but making this change just so no one re-makes the account with that name because that would make the link take to fake profile.

Updating my old deleted user with new

---

functions/cron/cron_fns.php
functions/multi_fns/loadup_fns.php
functions/multi_fns/process_fns.php
multiplayer_server/pr2.php

Preserve HH time on server restart

---

multiplayer_server/parts/Prizes.php
multiplayer_server/rooms/Game.php

strawberry jam

---

functions/multi_fns/client/ingame.php
multiplayer_server/CourseBox.php
multiplayer_server/rooms/LevelListRoom.php

Small fixes

---

functions/http_fns/http_data_fns.php

Users report awards being autoset on login no matter if they were just won or not. This fixes that reversion of the character loadout to contest prizes when ensuring the player has the prize.
More info: https://jiggmin2.com/forums/showthread.php?tid=2055

Fix contest prize awarding error on login

---

multiplayer_server/CourseBox.php

it can't be this simple, can it???

fix page highlighting?

---

functions/http_fns/pages/vault/vault_fns.php
http_server/download.txt
http_server/vault/vault.php
http_server/version.txt

release v157.1

---

functions/http_fns/pages/contests/part_vars.php
functions/http_fns/pages/vault/vault_fns.php
http_server/admin/part_ids.php
http_server/vault/vault.php
multiplayer_server/parts/Parts.php
multiplayer_server/parts/Prizes.php

- Celebrate the end of a decade with 50% off everything in the vault
- 2 new sets!!!

Happy holidays!

---

functions/multi_fns/process_fns.php
http_server/api/award_part.php

holiday stream special

---

multiplayer_server/CourseBox.php
multiplayer_server/rooms/Game.php
multiplayer_server/rooms/LevelListRoom.php

Small changes to combat a new botting technique.

Small changes

---

functions/http_fns/api_fns.php
functions/multi_fns/process_fns.php
http_server/api/award_part.php
multiplayer_server/Player.php

For use with pr2prize.swf (personal)

Fix part awarding API

---

.travis.yml
composer.lock

Good thought.
This reverts commits f8a9f11f26f97c647a2bfb48a17061f1d03c2d4e and eb37f83683d6ccd92efc1a3183fbd3b88e016543.

Revert travis config changes

---

config.php
functions/http_fns/pages/player_search_fns.php
http_server/level_data.php

something's happening

---

common/queries/guilds.php
http_server/guild_leave.php

Make them transfer ownership (or delete) first. Hooray for no more ownerless guilds!

Don't let guild owners leave their guild

---

common/queries/users.php
functions/http_fns/pages/admin/find_player_fns.php
http_server/admin/find_player.php

Lets admins search for users by keyword. Could be a feature for the public in the future. Maybe. :)

Let admins search the db for a name

---

common/queries/users.php
http_server/admin/find_player.php
http_server/admin/ip_deep_search.php
http_server/staff.php

For some reason, there are two columns for registration and active time/date and in the db. I plan to delete the dates (since they contain less data than the times) at a later time (no pun intended).

Convert active_date to time

---

http_server/guild_join.php

fix missing message on guild_join.php

---

common/queries/users.php
functions/http_fns/query_fns.php

makes the corresponding feature in 159 more secure
also, formatting on users.php

parse tags fn

---

functions/http_fns/output_fns.php
http_server/scripts/admin.js

a lil fanciness never hurt anyone, right?

make new admin tool option fancy

---

functions/http_fns/pages/vault/vault_fns.php
http_server/vault/vault.php
multiplayer_server/rooms/Game.php

Happy anniversary! For May 2/3, there will be a 20.08% vault sale and +4 times EXP multiplier.

Anniversary 2020

---

multiplayer_server/rooms/Game.php

one more edit

---

http_server/message_report.php

Don't let people report PMs they sent to themselves.
...why was this never addressed

PM reporting

---

functions/multi_fns/client/lobby.php
functions/multi_fns/multi_data_fns.php
multiplayer_server/ChatMessage.php
multiplayer_server/Player.php
multiplayer_server/RaceStats.php
multiplayer_server/rooms/Game.php

relocate modPower, groupStr

---

common/pdo_connect.php
common/queries/level_backups.php
common/queries/levels.php
common/queries/levels_reported.php
common/queries/messages.php
common/queries/messages_reported.php
functions/http_fns/http_data_fns.php
http_server/login.php
http_server/register_user.php

character encoding

---

functions/cron/cron_fns.php
http_server/favorite_levels_modify.php
http_server/levels_get.php
http_server/levels_get_reported.php

remove utf8_encode calls -- already encoded when returned from the db

hopefully final installment in encoding saga

---

common/queries/users.php
functions/http_fns/query_fns.php
functions/multi_fns/staff/demod.php
functions/multi_fns/staff/promote_to_moderator.php
http_server/ban_user.php
http_server/guild_edit.php
http_server/mod/purge_tokens.php
http_server/remove_level.php

phase out mod_power table

---

functions/multi_fns/process_fns.php
http_server/login.php

oh, those pesky control characters!

fix user status not updating

---

functions/multi_fns/utils.php

what a concept, a function that works

db_op: catch query errors properly

---

functions/common_fns.php
functions/multi_fns/staff/promote_to_moderator.php

Ability for mods to whitelist IPs that are falsely flagged

Let mods whitelist IPs

---

common/queries/bans.php
functions/http_fns/ip_api_fns.php
http_server/ban_user.php
http_server/mod/reports.php

Also:
- took out ban_user (alias for ban_insert) in favor of just using ban_insert
- fixed the IP API query fn (it switches properly now) -> travis is good SOMETIMES

Appease travis

---

functions/http_fns/pages/vault/vault_fns.php
http_server/vault/vault.php

Celebrate the end of summer with 25% off your vault purchases!
(I should really have a way to do this with only one file edit. And a way to add an expiration time in only one place. Hmm... something to work on later, I guess. 🤷‍♂️ )

Activate "Back To School Sale" in VoM

---

functions/http_fns/ip_api_fns.php
http_server/login.php
http_server/register_user.php

Changes all of the language "Ask a Mod" to "Contact a Mod", following the change on JV.

ask a mod -> contact a mod

---

multiplayer_server/rooms/Game.php

This did the exact opposite of what I wanted.

Fix arti removal

---

http_server/upload_level.php

Fixes a bug that skipped the check for hat attack mode when uploading a level.

Fix arti check for uploading hat attack

---

multiplayer_server/rooms/Game.php

Debugging an issue with hat replacement in hat attack mode.

Add debug code

---

multiplayer_server/rooms/Game.php

Better place in the file for debugging, I think.

Move debug code

---

multiplayer_server/rooms/Game.php

Add detection for if the player picking up the hats is the last to finish. If so, skip the countdown.

Modify countdown procedure for hat attack

---

functions/multi_fns/process_fns.php

Server owners showed as "Admin" on player popups prior to this fix.

Fix server owner display bug

---

multiplayer_server/rooms/Game.php

Oh, php. Why do you hurt me so?

Hopefully fix no hat error

---

functions/common_fns.php
functions/http_fns/pages/admin/set_campaign_fns.php
functions/http_fns/query_fns.php
http_server/admin/part_ids.php
http_server/download.txt
http_server/version.txt
multiplayer_server/parts/Parts.php
multiplayer_server/parts/Prizes.php
multiplayer_server/rooms/Game.php

161.1 release

---

functions/cron/cron_fns.php

Not much truth to that one
ba-dum-tss

Fix function call

---

common/env.example.php
functions/http_fns/pages/vault/vault_fns.php
http_server/vault/vault.php

This should've been done a long time ago. Better late than never, I suppose!

Move vault sale info to env.php

---

common/manage_socket/restart_server.php
functions/common_fns.php
functions/http_fns/api_fns.php
functions/http_fns/http_data_fns.php
functions/http_fns/query_fns.php
functions/multi_fns/artifact_fns.php
functions/multi_fns/process_fns.php
http_server/admin/ip_deep_search.php
http_server/admin/player_deep_logins.php
http_server/api/award_part.php
http_server/contests/contests.php
multiplayer_server/Player.php
multiplayer_server/pr2.php

Lets me award parts with a special program. :)
(This also removes the redundant ternary statements -- i.e., `? true : false` and `? false : true`)

Enable part awards API

---

common/env.example.php
functions/http_fns/api_fns.php

Hey, guess what? It helps when you use the right variable name!

Fix part awards API

---

http_server/api/award_part.php

Adds logging for prize awards via the award_part.php API. Also fixes error handling so that any failure to award the part is caught and handled as an error (`{"success": false, "error":"Error message"}`).

Log API prize awards

---

.gitignore
functions/http_fns/check_local_fn_example.php
functions/http_fns/gen_http_fns.php
functions/http_fns/http_data_fns.php

Trying some things

---

functions/multi_fns/loadup_fns.php
functions/multi_fns/utils.php

Even more 162 beta fixes

---

http_server/download.txt
http_server/vault/vault.php
http_server/version.txt

162 Release

---

http_server/download.txt
http_server/version.txt

This release is a hotfix for a bug causing lag in races.

162.1.1 Release

---

common/cron/daily.php
common/queries/rank_token_rentals.php
common/queries/users.php
functions/cron/cron_fns.php

Fixes the rank-related problems outlined in: https://jiggmin2.com/forums/showthread.php?tid=3415

Update rank after rank token rentals expire

---

multiplayer_server/Player.php

Fixes the part-related problems outlined in: https://jiggmin2.com/forums/showthread.php?tid=3415

Reset shown part before saving if a temp item

---

common/queries/levels.php

Fixes concerns 1 and 3 listed in this thread: https://jiggmin2.com/forums/showthread.php?tid=3419
In conjunction with this pull, the structure of the levels table has been changed to InnoDB.

Beef up level searching

---

common/queries/levels.php

Fix concern 2 listed in this thread: https://jiggmin2.com/forums/showthread.php?tid=3419
Thanks Dexterity!

Further beef up level searching

---

http_server/download.txt
http_server/upload_level.php
http_server/version.txt

164 Release

---

functions/multi_fns/artifact_fns.php
multiplayer_server/rooms/Game.php

Disable EXP/bubbles awards from artifact

---

functions/common_fns.php
functions/cron/cron_fns.php
functions/http_fns/pages/admin/set_campaign_fns.php
functions/multi_fns/artifact_fns.php
http_server/admin/part_ids.php
http_server/download.txt
http_server/get_player_info.php
http_server/version.txt
multiplayer_server/Player.php
multiplayer_server/parts/Parts.php
multiplayer_server/parts/Prizes.php
multiplayer_server/rooms/Game.php

165 Release

---

multiplayer_server/ChatMessage.php
multiplayer_server/rooms/Game.php

Allows admins to see more data when they're debugging a player online.

More info on admin player debug

---

functions/http_fns/query_fns.php
http_server/delete_level.php
http_server/upload_level.php

Modernize the check that makes sure someone isn't modifying or deleting the artifact level such that it includes scheduled levels.

Update artifact level modify/delete check

---

functions/http_fns/ip_api_fns.php

Hopefully gets rid of some of the false positives.

Loosen proxy/VPN check

---

http_server/download.txt
http_server/version.txt

165.1 Release

---

common/queries/campaigns.php
functions/common_fns.php
functions/http_fns/pages/admin/set_campaign_fns.php
functions/http_fns/rand_crypt/Encryptor.php
http_server/admin/part_ids.php
http_server/admin/set_campaign.php
http_server/download.txt
http_server/version.txt
multiplayer_server/parts/Parts.php
multiplayer_server/parts/Prizes.php

166 Release

---

functions/http_fns/query_fns.php
functions/http_fns/rand_crypt/Encryptor.php
http_server/api/send_discord_verification.php
http_server/backups/backups.php

Fast forward repo to current server state

---

http_server/download.txt
http_server/version.txt

167 Release

---

functions/http_fns/query_fns.php
functions/multi_fns/process_fns.php
http_server/login.php
multiplayer_server/Player.php

- Send a "welcome back" PM if the user has been inactive for at least 2 months.
- Edit the welcome PM to include links to Discord and JV
- Edit the guest welcome popup to include a link to Discord

Slightly change welcome messages

---

http_server/download.txt
http_server/version.txt

167.1 Release

---

http_server/download.txt
http_server/version.txt
multiplayer_server/Player.php

168.0 Release

---

http_server/download.txt
http_server/version.txt

168.0.1 Release

---

http_server/download.txt
http_server/version.txt

168.0.2 Release

---

.gitignore
common/queries/vault_coins_orders.php
functions/http_fns/pages/admin/award_coins_fns.php
http_server/admin/award_coins.php

Allows admins to award coins to players in a minimal capacity. The idea is that more significant awards will be done manually by me if needed.

Award coins script

---

functions/http_fns/pages/admin/award_coins_fns.php
functions/http_fns/pages/admin/player_deep_info_fns.php
http_server/admin/award_coins.php

Adds a link to award coins on the admin player details page.

Add player_deep_info passthrough

---

http_server/admin/player_deep_info.php

Adds a link to the admin player search on the player_deep_info page.

Add player_deep_info passthrough to find player

---

functions/http_fns/output_fns.php

Adds a nav link to the admin menu to update levels.

Add nav link to admin/update_level.php

---

functions/http_fns/pages/admin/level_deep_info_fns.php
http_server/download.txt
http_server/scripts/admin.js
http_server/version.txt

168.1 Release

---

http_server/api/send_discord_verification.php

Updates the script to allow requests from users with no discriminator.

Fix discord linking

---

multiplayer_server/rooms/Game.php

Fixes a potential server crash if the user gets d/c'd before the message can be sent.

Fix server crash on super fast botting check

---

http_server/download.txt
http_server/version.txt

168.2 Release

---

http_server/download.txt
http_server/version.txt

Reverts PR2 v168.2 release due to LE-breaking issues.

Revert "168.2 Release"

---

http_server/download.txt
http_server/version.txt

168.2.1 Release
